### ISSUE TITLE
How to set brute force ?

### ISSUE THREAD

**Issue by guga330** [Tommrodrigues/WiFiCrack#3]
Hey. I'm having trouble on how to add brute force. The default on the WiFiCrack is for me to add a dictionary. It will to directly to hash and start the cracking based on the dictionary I provided. I would like to use brute force, but I am having trouble on how to add it so I can type my brute force command so I will automatically open hashcat and use the bruteforce command.

**Comment by phenotypic** [comment]
Hi there,

Native brute force option is something I'm looking to add to the script in the near future. For now however, you can simply use the `-k` flag and then cancel the script once the capture has completed, just before dictionary cracking begins.

This will leave the `capture.hccapx` file in the directory. From here, you can manually perform any sort of cracking you desire on this file.

**Comment by guga330** [comment]
Hey! I understood and it worked! Hope to see that brute force option soon haha. Hey so I'm new to hashcat, so I have an issue that I can't seem to find an answer. I was hoping you could help me out. I run your shell script and I am able to get the handshakes and create the capture.hccapx file. Now I want to use brute force to pentest and see in how much time I will able to crack the password.
I use the following code:

hashcat -a 3 -m 2500 /Users/johnnaves/WiFiCrack/capture.hccapx ?l?l?l?l?l?l?l?l


Which would try to guess an 8 digit password with only lowercase letters (?l?l?l?l?l?l?l?l). My issue is that when I launch the code it estimates a total of 80 days to be able to run through all the possibilities. I'm assuming that there is something wrong with the GPU speed configuration, but I don't know how I would fix this. I'm running a MacBook Pro 15' 2017.

Any help would be appreciated! Thank you for the attention. =)

**Comment by phenotypic** [comment]
I'm no expert on hashcat or cracking in general, but brute force is just that - it takes considerably more computing power than a dictionary search. 8 lowercase letters is already 26^8 possible combinations, so 80 days is no real surprise.
