### ISSUE TITLE
ERROR (airport failure): Please run WiFiCrack again...

### ISSUE THREAD

**Issue by jason19970210** [Tommrodrigues/WiFiCrack#4]
As title above !! 

Environment : macOS 10.15.6 Catalina (2019 Mid MacBook Pro 13')
Shell had tried : zsh / bash

```
$ which airport
/usr/local/bin/airport
```
```
$ airport
Usage: airport <interface> <verb> <options>

	<interface>
	If an interface is not specified, airport will use the first AirPort interface on the system.

	<verb is one of the following:
	prefs	If specified with no key value pairs, displays a subset of AirPort preferences for
		the specified interface.

		Preferences may be configured using key=value syntax. Keys and possible values are specified below.
		Boolean settings may be configured using 'YES' and 'NO'.

.... 
```
( Means I have airport in my MacBook !! )

Please help !!
Thanks a lot.

**Comment by phenotypic** [comment]
Hi there, the script expects the `airport` executable to be in `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport`, not `/usr/local/bin/airport`.

If you don't have `airport` there as well, change all instances of the path in the script to where your executable is located.
