### ISSUE TITLE
"ERROR: Cannot execute mergecap" even if wireshark is installed

### ISSUE THREAD

**Issue by ukushu** [Tommrodrigues/WiFiCrack#5]
"[!] ERROR: Cannot execute mergecap."

Wireshark manually installed from offsite. Opened, and successfully runned;

macOS: 12.2 (21D49)
MacBook Air (M1, 2020)
Wireshark: Version 3.6.1 (v3.6.1-0-ga0a473c7c1ba)

**Comment by phenotypic** [comment]
Hi there, unfortunately I no longer actively maintain this project so I can only offer limited guidance. However, as the error message you posted suggests, `mergecap` is not available to execute on your machine. Test this by running `mergecap` in your Terminal.

The `README` for this project specifies that you must have Wireshark v2.6.12 installed. You list yours as v3.6.1.

I think `mergecap` has been removed from Wireshark package in more recent versions. You may have more luck obtaining `mergecap` by installing Wireshark through [brew](https://brew.sh/): `brew install wireshark`

Either way, I would recommend checking out [WiFiCrackPy](https://github.com/phenotypic/WiFiCrackPy) which I developed as the successor to this project. It is much more streamlined and does not utilise `mergecap`.
