### ISSUE TITLE
The plugin 2500 is deprecated and was replaced with plugin 22000.

### ISSUE THREAD

**Issue by dvlop** [Tommrodrigues/WiFiCrack#7]
current stable version hashcat: 6.2.5

Error: The plugin 2500 is deprecated and was replaced with plugin 22000. For more details, please read: https://hashcat.net/forum/thread-10253.html

**Comment by phenotypic** [comment]
Thanks for opening this issue. This project is no longer actively maintained.

Instead, as per the `README`, please use [WiFiCrackPy](https://github.com/phenotypic/WiFiCrackPy) which utilises the new 22000 method.
