### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by RogierVC** [Tommrodrigues/WiFiCrack#9]
Script is giving me this output...

```
[*] Scanning for Wi-Fi networks...
WifiCrack.sh: line 170: syntax error near unexpected token `<'
WifiCrack.sh: line 170: `done < <(sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s | tail -n +2 | sort)'
```

**Comment by phenotypic** [comment]
Hi there, I was unable to replicate this error. Please refer to [WiFiCrackPy](https://github.com/phenotypic/WiFiCrackPy) which has been developed as the successor to WiFiCrack and is actively maintained.
